"""Celery task names and queue routes — single source of truth for API and workers."""

from aqa_shared.queue.names import (
    QUEUE_ANALYZE,
    QUEUE_DESIGN,
    QUEUE_DISCOVER,
    QUEUE_EXECUTE,
    QUEUE_GENERATE_SCRIPTS,
    QUEUE_REPORT,
)

CELERY_TASK_PREFIX = "aqa.tasks"

CELERY_TASK_DISCOVER = f"{CELERY_TASK_PREFIX}.discover"
CELERY_TASK_DESIGN = f"{CELERY_TASK_PREFIX}.design"
CELERY_TASK_GENERATE_SCRIPTS = f"{CELERY_TASK_PREFIX}.generate_scripts"
CELERY_TASK_EXECUTE = f"{CELERY_TASK_PREFIX}.execute"
CELERY_TASK_REPORT = f"{CELERY_TASK_PREFIX}.report"
CELERY_TASK_ANALYZE = f"{CELERY_TASK_PREFIX}.analyze"
CELERY_TASK_CLEANUP_ARTIFACTS = f"{CELERY_TASK_PREFIX}.cleanup_artifacts"

CELERY_TASK_NAMES: tuple[str, ...] = (
    CELERY_TASK_DISCOVER,
    CELERY_TASK_DESIGN,
    CELERY_TASK_GENERATE_SCRIPTS,
    CELERY_TASK_EXECUTE,
    CELERY_TASK_REPORT,
    CELERY_TASK_ANALYZE,
    CELERY_TASK_CLEANUP_ARTIFACTS,
)

CELERY_TASK_ROUTES: dict[str, str] = {
    CELERY_TASK_DISCOVER: QUEUE_DISCOVER,
    CELERY_TASK_DESIGN: QUEUE_DESIGN,
    CELERY_TASK_GENERATE_SCRIPTS: QUEUE_GENERATE_SCRIPTS,
    CELERY_TASK_EXECUTE: QUEUE_EXECUTE,
    CELERY_TASK_REPORT: QUEUE_REPORT,
    CELERY_TASK_ANALYZE: QUEUE_ANALYZE,
    CELERY_TASK_CLEANUP_ARTIFACTS: QUEUE_REPORT,
}

# Celery worker config expects this shape.
TASK_ROUTES = {name: {"queue": queue} for name, queue in CELERY_TASK_ROUTES.items()}
