"""Re-export Celery task and queue names from aqa_shared (backward-compatible aliases)."""

from aqa_shared.celery.task_names import (
    CELERY_TASK_ANALYZE,
    CELERY_TASK_DESIGN,
    CELERY_TASK_DISCOVER,
    CELERY_TASK_EXECUTE,
    CELERY_TASK_GENERATE_SCRIPTS,
    CELERY_TASK_REPORT,
    CELERY_TASK_ROUTES,
    TASK_ROUTES,
)
from aqa_shared.queue.names import (
    QUEUE_ANALYZE,
    QUEUE_DESIGN,
    QUEUE_DISCOVER,
    QUEUE_EXECUTE,
    QUEUE_GENERATE_SCRIPTS,
    QUEUE_REPORT,
)

TASK_DISCOVER = CELERY_TASK_DISCOVER
TASK_DESIGN = CELERY_TASK_DESIGN
TASK_GENERATE_SCRIPTS = CELERY_TASK_GENERATE_SCRIPTS
TASK_EXECUTE = CELERY_TASK_EXECUTE
TASK_REPORT = CELERY_TASK_REPORT
TASK_ANALYZE = CELERY_TASK_ANALYZE

# Maps task name -> queue name (string values).
TASK_QUEUE_ROUTES = CELERY_TASK_ROUTES

__all__ = [
    "TASK_DISCOVER",
    "TASK_DESIGN",
    "TASK_GENERATE_SCRIPTS",
    "TASK_EXECUTE",
    "TASK_REPORT",
    "TASK_ANALYZE",
    "QUEUE_DISCOVER",
    "QUEUE_DESIGN",
    "QUEUE_GENERATE_SCRIPTS",
    "QUEUE_EXECUTE",
    "QUEUE_REPORT",
    "QUEUE_ANALYZE",
    "TASK_ROUTES",
    "TASK_QUEUE_ROUTES",
]
